name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          npx cypress run --browser ${{ matrix.browser }} --spec "cypress/e2e/gui/authentication/loginGUI.cy.js","cypress/e2e/api/authentication/loginAPI.cy.js" --reporter mochawesome --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true

      - name: Merge test reports
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts-${{ matrix.browser }}
          path: |
            cypress/videos/
            cypress/screenshots/
            cypress/reports/mochawesome/
            mochawesome-report/

  cd:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        browser: [chrome, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: cypress-artifacts-${{ matrix.browser }}
          path: ./

      - name: Verifies content of files after download
        run: |
          echo "Listing downloaded files:"
          ls -R ./cypress

      - name: Copy artifacts
        run: |
          mkdir -p ./public/${{ matrix.browser }}/videos
          mkdir -p ./public/${{ matrix.browser }}/screenshots
          mkdir -p ./public/${{ matrix.browser }}/mochawesome-report

          echo "Copy mp4 videos and paste it into one folder"
          ls -R ./cypress/videos/ || true
          find ./cypress/videos/ -name "*.mp4" -exec cp {} ./public/${{ matrix.browser }}/videos/ \;

          echo "Content of ./public/videos after copy"
          ls -R ./public/${{ matrix.browser }}/videos || true

          cp -r ./cypress/screenshots/* ./public/${{ matrix.browser }}/screenshots/ || true
          cp -r ./cypress/reports/mochawesome/* ./public/${{ matrix.browser }}/ || true
          cp -r ./cypress/mochawesome-report/* ./public/${{ matrix.browser }}/mochawesome-report/ || true

      - name: Verifies content before deploy
        run: |
          echo "Content of ./public/${{ matrix.browser }} before deploy:"
          ls -R ./public/${{ matrix.browser }} || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/${{ matrix.browser }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'


