name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run specific Cypress tests
        run: |
          npx cypress run --spec "cypress/e2e/gui/authentication/loginGUI.cy.js","cypress/e2e/api/authentication/loginAPI.cy.js" --reporter mochawesome --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true
        
      - name: Merge test reports
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Copy Cypress Artifacts and Reports to Public folder
        if: always()
        run: |
          mkdir -p ./public/videos
          mkdir -p ./public/screenshots
          mkdir -p ./public/mochawesome-report
    
          echo "Copy mp4 videos and paste it into one folder"
          ls -R cypress/videos/ || true
          cp -r cypress/videos/**/*.mp4 ./public/videos/ || true
    
          echo "Content of ./public/videos after copy"
            ls -R ./public/videos || true
    
          cp -r cypress/screenshots/* ./public/screenshots/ || true
          cp -r cypress/reports/mochawesome/* ./public/ || true
          cp -r mochawesome-report/* ./public/mochawesome-report/ || true

      - name: Deploy Mochawesome Report and Cypress Artifacts to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
